# Usa una imagen base de Python  
FROM python:3.9-slim  
  
# Establece el directorio de trabajo  
WORKDIR /app  
  
# Copia los archivos de requisitos  
COPY requirements.txt ./  
COPY .env ./  
  
# Instala las dependencias  
RUN pip install --no-cache-dir -r requirements.txt  
  
# Copia el contenido del proyecto  
COPY . .  
  
# Expone el puerto 5000  
EXPOSE 5000  
  
# Comando para ejecutar la aplicación  
CMD ["flask", "run", "--host=0.0.0.0"]  
